services:
  postgres:
    image: postgres:14.10
    container_name: hello_db
    environment:
      POSTGRES_DB: hello
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: